Flagsmith/flagsmith-js-client

- bullet-train-core.js
This fix #3 by passing the proper object structure to handleResponse when getFlags() is called without an identity.
> fix #3 client-does-not-return-flags

- index.react-native.js
The bullet-train-react-native client is using AsyncStorage from React Native core, which has been deprecated starting from React Native version 0.59 as part of the Lean Core initiative. The way to move forward is to use the @react-native-community/async-storage library instead.
This is causing issues/conflicts for projects (like mine) that is using the new library.
We can fix that issue by using the AsyncStorage from @callstack which already depends on the correct library.
> Use AsyncStorage from @callstack for React Native

- README.md
current description of `onChange` gives an impression of some sort of websocket/realtime update capability, but that's not the case
> fix: onChange method description to be accurate

- bullet-train-core.js
When a cache is being used and then for some reason the `environmentID` changes, we get stuck in the old `environmentID` and the new value passed in `init` is ignored. This PR intends to solve that checking by both `api` and `environmentID`.
> Invalidate cache when environmentID changes

- bullet-train-core.js
For example:
```js
onChange: (oldFlags) => {
if (oldFlags === this.flags) {
console.log("After the first call to onChange, this condition is always true!");
}
}
```
> Fix oldFlags assignation order

- bullet-train-client/index.d.ts
- index.d.ts
- react-native-bullet-train/index.d.ts
I noticed that while trying to use the following code sample in Angular, I hit a problem:
```
bulletTrain
.init({
api: environment.bulletTrainAPI,
environmentID: environment.bulletTrainEnvID,
onChange: (oldFlags: Flags) => {
this.flags = oldFlags;
this.onChange.next();
},
})
.then(() => bulletTrain.identify(identifyId))
.then(() => bulletTrain.setTrait('country_code', environment.countryCode));
```
It was complaining about not having an `AsyncStorage` key (and that `init` didn't return a promise).
This PR fixes these minor problems and makes the above code sample usable
> Fix minor typing errors

- flagsmith-core.js
Throwing exception in the Flagsmith.init (https://github.com/Flagsmith/flagsmith-js-client/blob/master/flagsmith-core.js#L181) function causes onError handler not fired. Adding .catch block for init function solves the problem.
> fix for #75

- flagsmith-core.js
Prevent GET request to inject header "content-type", it's not working, it's always set the "content-type" header, because when it's a GET method the variable method it's undefined and the condition is never true.
> Prevent GET request to inject header "content-type"

- index.d.ts
We stumbled onto some typing errors with the IBulletTrainFeature when using `getValue()` because this latter is `string|number|boolean`. This tries to fix this.
> Change type of value

- flagsmith-core.js
- index.d.ts
Added a header parameter to `flagsmith.init`. Accepts `{header1: "data1", header2: function2()}`.
We're planning to run flagsmith behind a gateway and the gateway will prevent unauthorised identity / trait manipulation via clients.
> Added headers parameter which can be used to pass custom headers

- examples/angular/package-lock.json
- examples/deno/README.md
- examples/deno/app/flagsmith.ts
- examples/deno/app/index.ts
- examples/deno/app/router.ts
- examples/deno/package.json
- examples/react-native/README.md
- examples/react/README.md
- flagsmith/index.d.ts
- flagsmith/package.json
- index.d.ts
- package.json
- react-native-flagsmith/README.md
- react-native-flagsmith/index.d.ts
- react-native-flagsmith/package.json
"BULLET_TRAIN_DB" and "BULLET_TRAIN_EVENT" are keys for local storage so will remain for now, rolling a major version for vanity
IBulletTrainFeature has been deprecated but will have to remain to allow for a non-breaking version due to people likely importing it.
> Remove bullet train references

- flagsmith-core.js
> fix: guard against null `onError` in init

- flagsmith-core.js
I'm initiating `flagsmith` in the following way:
```javascript
flagsmith
.init({
environmentID: flagsmithEnvironmentId,
onChange: (e) => { console.log('onChange', e) },
onError: (e) => { console.log('onError', e) },
cacheFlags: true,
enableAnalytics: true,
enableLogs: false,
AsyncStorage,
})
.catch((e) => { console.log('catch', e) })
```
`flagsmith` is initiated correctly, but `onError` catches an error immediately after initiating: `Uncaught TypeError: PromiseResolve called on non-object`.
Apparently this error arises because somewhere in the code it's passing a `Promise.resolve` as arg to another function, which then calls it. If you want to reproduce it minimally, please run this code below in any JavaScript engine:
```javascript
const f = (g) => g(); f(Promise.resolve);
```
Glancing …
> Fix error being thrown on init

- react/index.tsx
The typescript definitions for the `useFlags` mark the traits array as optional. However, if you omit the array when using the hook, you'll be faced with the following warning which comes from the `flagsAsArray` function.
> 'Flagsmith: please supply an array of strings or a single string of flag keys to useFlags'
Changing the traits to default to an empty array in the function signature would remove the error and still keep the types the same. We just have to change `?:` to `:` otherwise TS will complain that you can't have a `?` and a default value.
> Default traits to empty array in useFlags

- flagsmith-core.ts
This PR is a proposal to fix issue https://github.com/Flagsmith/flagsmith-js-client/issues/103. The idea is to just not condition on `getFlagInterval` when deciding whether to run `getFlags` after a call to `identify` or `logout`.
> Do not depend on listener to run getFlags

- flagsmith-core.ts
This only shows up if you have onError set log out errors.  the message that comes back: `TypeError: t is not a function`
> incrementTrait throws an error

- react/index.d.ts
This seems to fix #115 for me locally, and should have no breaking changes for React 17
> Fix types for React 18

- flagsmith-es/react/index.d.ts
- flagsmith/react/index.d.ts
- react/index.tsx
In #116 I did not realize these types are re-defined in a few other places. While that came as a bit of a surprise, here is a fix to just get things correctly typed everywhere. 
A longer-term solution would obviously not to define the same types more than once.
> Update provider children types in other files

- lib/flagsmith-es/package-lock.json
- lib/flagsmith-es/package.json
- lib/flagsmith/package-lock.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package-lock.json
- lib/react-native-flagsmith/package.json
- package-lock.json
- package.json
Currently, there is an inconsistency in the package licence between GitHub and NPM. The packages' license in NPM should be BSD-3 as in GitHub.
> fix: Set BSD-3 Clause as license type in package.json

- rollup.config.js
This PR adjusts the Rollup names to flagsmith-react and react-native-flagsmith-react for better UMD support
> Adjust rollup names

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
Allows the following usage:
```ts
flagsmith.getValue('refresh_interval', { fallback: 10000 });
```
Fixes #212
> Respect `fallback` also without `json` flag in `getValue`

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
Nextjs is polyfilling fetch to always use cache regardless of freshness. https://nextjs.org/docs/app/building-your-application/caching#fetch
The browser looks for a matching request in its HTTP cache. If there is a match, fresh or stale, it will be returned from the cache. If there is no match, the browser will make a normal request, and will update the cache with the downloaded resource.
We'd always want cache off as it's handled at the local storage level, this PR turns that feature off.
> Add no-cache option

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
The Open feature client needs to set traits silently, without calling setTraits(). This allows you to send traits in the next call based on the traits provided in setState.
> chore: add withTraits when setting state

- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- types.d.ts
The generic type for onChange was undefined, this PR allows it to be specified.
> fix: onChange types

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/init.test.ts
Clears out traits when identifying over previous identity.
> fix: clear traits when identifying over previous identity

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
The SDK ignores responses that have come from an identity that has since changed. This was causing uncaught errors upstream. This PR adjusts the SDK to silently handle the errors, they will still be logged if enableLogs is true.
The easiest way to replicate this is by identifying multiple times with network throttling.
> fix: Silently handle request response miss-matches

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/functions.test.ts
- types.d.ts
This change solves https://github.com/Flagsmith/flagsmith-js-client/issues/243 by adding a `fallback` option to `hasFeature`, instead of changing how `defaultFlags` works. It also deprecates the current way of using `skipAnalytics` but preserves backwards compatibility.
I chose to move `skipAnalytics` into an option property instead of a boolean parameter for both `getValue` and `hasFeature`. If we chose to only add parameters to `hasFeature` and not deprecate anything, these would be our options:
1. Add a `{ fallback: boolean }` parameter
```ts
// forces you to specify a value for skipAnalytics, which is weird
hasFeature("my_bool", false, { fallback: true })
// looks inconsistent with getValue
getValue("my_feat", { fallback: "foo" }, true)
```
2. Add a boolean parameter for the fallback …
> Support fallback for hasFeature, add options.skipAnalytics

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/cache.test.ts
Fixes https://github.com/Flagsmith/flagsmith-js-client/issues/242. flagsmith.init traits will be merged with cache when it is read.
> fix: Merge flagsmith.init traits with cached values

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/react.test.tsx
- test/test-constants.ts
If flagsmith.init resolved after flagsmith.identify it would cause a react application to see ``{}`` for the flags, the sdk will now ignore any API responses that do not match the current identity.
> fix: race condition within flagsmith.init responses

- flagsmith-core.ts
- test/cache.test.ts
- test/default-flags.test.ts
- test/react.test.tsx
- test/test-constants.ts
- types.d.ts
A limitation was found in the `clientSide cacheFlags` implementation. The issue arises because the same key is always used in `localStorage` cited in #201, which can lead to conflicts when the system is used in the context of micro frontends (MFEs) or with multiple instances. This key competition in `localStorage` can cause negative effects, such as data being overwritten or cache inconsistencies.
To address this issue, it was proposed to allow the `localStorage` key name to be explicitly defined or for it to take into account the `environmentID`. This would solve the problem by ensuring that each instance or environment has a unique key, preventing conflicts.
1. **Concatenating `environmentID` to the `localStorage` Key:** To resolve the initial problem, the key used in `localStorage` was …
> #201 (feat): added envId to the storage key and added property to cacheOptions to customize the key

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/cache.test.ts
- types.d.ts
Closes #250 with an additional `cacheOptions.loadStale` to load the current cached state even if it is expired.
> add loadStale cache option to load already expired cache data

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/cache.test.ts
I think I missed this in the #251 PR.
In this PR I added tests and code to maintain the behaviour of getting from the api when the cache expired and after loading the stale cache.
There is bad case where you might end up with a forever stale cache by using the `loadStale: true`, when you expected that it always fetch when the cache has expired..
cc: @kyle-ssg
> fix fetch from api after loading stale cache when skip api set

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
This fixes incorrect `init` behaviour that prevented users from using `identify` prior to calling `init`.
> fix: Evaluation context overwritten on init

- flagsmith-core.ts
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- types.d.ts
> fix: Incorrect argument type, interface extension

- flagsmith-core.ts
- test/init.test.ts
Closes https://github.com/Flagsmith/flagsmith-js-client/issues/249
When the local cache is populated or when default flags are provided, `flagsmith.init` does not reject if the call to edge proxy fails; however, an uncaught exception gets thrown which is difficult to catch in user code. This change allows the error to be caught within Flagsmith (logging `Exception fetching cached logs` when verbose mode is on).
> fix: Handle uncaught fetch exception

- flagsmith-core.ts
- lib/flagsmith-es/package-lock.json
- lib/flagsmith-es/package.json
- lib/flagsmith/package-lock.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package-lock.json
- lib/react-native-flagsmith/package.json
- test/cache.test.ts
- test/default-flags.test.ts
- test/init.test.ts
- test/react.test.tsx
- test/test-constants.ts
- types.d.ts
This PR includes 2 changes: 
1. Re-adds the changes from #252 which were previously reverted in #258 
2. Bumps the version from 7.0.2 to 8.0.0
> Release 8.0.0

- flagsmith-core.ts
> Fix: Keep identity identifier in handleResponse

- react.tsx
Replaces ``React.ReactElement[] | React.ReactElement`` in favour of ``React.ReactNode``
> chore: add ReactNode type

- types.d.ts
This pull request un-deprecates `setTrait`, `setTraits` and `identify` to match current documentation
Ref: https://github.com/Flagsmith/flagsmith-js-client/issues/275
> fix: Un-deprecate `setTrait`, `setTraits` and `identify`

- lib/flagsmith-es/README.md
- lib/flagsmith-es/package-lock.json
- lib/flagsmith-es/package.json
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
This adds a post-install deprecation notice to flagsmith-es, https://github.com/Flagsmith/flagsmith-js-client/pull/280 will make the package no longer necessary
> chore: Deprecate flagsmith-es

- index.d.ts
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- react.d.ts
This PR fixes the following problems:
- Autocomplete was not working
- Users were having issues with v9.0.0 (`Types are found in 'react.d.ts', but this result could not be resolved when respecting package.json "exports"`)
- `Cannot find module './evaluation-context' or its corresponding type declarations.` https://github.com/Flagsmith/flagsmith-js-client/issues/283
> fix: Types not being exported and autocomplete not working

- flagsmith-core.ts
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/init.test.ts
- utils/ensureTrailingSlash.ts
Ensures that the flagsmith base url has a single trailing /. Whilst I considered using JavaScript's built in URL API, there's a chance that a polyfil would be needed to guarantee exact same behaviour so this seemed far less risky.
> fix: Handle API URL with or without trailing slash

- flagsmith-core.ts
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
Fix ts class field conflicting type definitions
This was causing issues when defining `flagsmith.json` type to IState as reported in #292
> fix: conflicting ts field type

- flagsmith-core.ts
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/init.test.ts
- types.d.ts
Ref:  [#2479](https://github.com/Flagsmith/flagsmith/issues/2479)
* This pull request includes changes to the `flagsmith-core.ts` file to add support for `appName` and `appVersion` in the `Flagsmith` class.
* Updated the `getJSON` method to include `X-Customer-Application-Name` and `X-Customer-Application-Version` headers if `appName` and `appVersion` are provided.
> feat: send client info to Flagsmith

- README.md
- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- package.json
- test/types.test.ts
- types.d.ts
Closes https://github.com/Flagsmith/flagsmith-js-client/issues/307
- fix typos in type definition file and test file
- add development details to readme and `package.json`
> Fix: typo in type definition file

- lib/flagsmith/package.json
- lib/react-native-flagsmith/package.json
- test/types.test.ts
- types.d.ts
Thanks for submitting a PR! Please check the boxes below:
Type fix for #314 
It was done for react but not JS client
- Reworked client types to use `FKey<F>` that includes keyof F
- Added tests
- Locally
- Tests
```
interface MyFeatureInterface {
featureOne: string;
featureTwo: boolean;
}
```
- Link js-client with local app
- create new flagsmith client as `const typedFlagsmith = flagsmith as IFlagsmith<MyFeatureInterface>;` 
- Try out different types combinations
> fix: updated-interface-flags-for-javascript-client

- types.d.ts
Follow-up on #315
This PR adds another type improvement:
- OnChange using correct `FKey<K>` type
- FValue checking for record type first to set a `F[K]` type
> fix: improved-on-change-and-fvalue-types
